# Generated by Django 4.1.3 on 2023-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('D', 'DEPOSITE'), ('T', 'TRANSFER')], default='D', max_length=50),
        ),
    ]
