# Generated by Django 4.1.3 on 2023-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Failure', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('DEPOSITE', 'DEPOSITE'), ('TRANSFER', 'TRANSFER')], default='D', max_length=50),
        ),
    ]
